version: "3.1"
services:
    webserver:
        build:
          context: ./app/
          dockerfile: DockerFile
        image: puckel/docker-airflow:latest
        container_name: paxmile_airflow
        volumes:
          - ./dags/:/usr/local/airflow/dags
        ports:
          - 8080:8080
        networks:
          - backend
        restart: always
        depends_on:
          - db
    www:
        build: .
        container_name: paxmile_www
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - backend
    db:
        image: mysql:8.0
        container_name: paxmile_db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: climberworld
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./persistent:/var/lib/mysql
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: paxmile_phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:

networks:
    backend:
        driver: "bridge"
