version: "3"
services:
    webserver:
        build:
            context: ./app/
            dockerfile: Dockerfile
        image: puckel/docker-airflow:latest
        container_name: paxmile_airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - 8080:8080
        networks:
            - backend
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: testdb
        container_name: paxmile_mysql
        ports:
            - 3306:3306
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: paxmile_phpmyadmin
        links: 
            - mysqldb:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: helloworld 
        networks:
            - backend
    www:
        build:
            context: ./php/
            dockerfile: Dockerfile
        container_name: paxmile_www
        ports: 
            - "8001:80"
        volumes:
            - ./php/www:/var/www/html/
        links:
            - mysqldb:db
        networks:
            - backend
networks:
  backend:
    driver: "bridge"